[package]
name = "s2dc"
version = "0.1.0"
edition = "2018"

[dev-dependencies]
assert_matches = "1.5.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dev-dependencies.macroquad]
version = "0.3.7"
