[package]
name = "s2dc"
version = "0.1.0"
edition = "2021"

[dev-dependencies]
egui-macroquad = "0.15.0"
assert_matches = "1.5.0"

[dependencies]
num-traits = "0.2.15"

[features]
serde = ["dep:serde"]

[dependencies.serde]
version = "1.0"
features = ["derive"]
optional = true
